baseURL = "http://cadelwatson.com/"
languageCode = "en-us"
sectionPagesMenu = "main"
theme = "SimpleTheme"
title = "Cadel Watson"
[[menu.main]]
identifier = "racing"
name = "Racing"
title = "Racing"
url = "/racing/"
weight = 10
[[menu.main]]
identifier = "projects"
name = "Projects"
title = "Projects"
url = "/projects/"
weight = 1
[[menu.main]]
identifier = "programming"
name = "Programming"
title = "Programming"
url = "/programming/"
weight = 9
