---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: textarea
  name: description
  label: Description
  config:
    required: true
pages:
- books/red-storm-rising-by-tom-clancy.md
- books/eating-animals-by-jonathan-safran-foer.md
- books/the-sympathizer.md
- environment/making-microinsurance-possible.md
